name: workflow Version Project

on: push

env:
  PROJECT_VERSION: 1.0.0

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: version project
        run: echo PROJECT_VERSION 

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: zulu

      - name: build jar
        run: mvn clean package -DskipTests
