name: workflow Version Project

on: 
  push:
    branches:
      - main

env:
  PROJECT_VERSION: 1.0.0
  MAVEN_OPTS: "-Dmaven.repo.local=/home/runner/work/lib"
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: version project
        run: echo PROJECT_VERSION 

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Cache
        uses: actions/cache@v4.1.2
        with:
          path: /home/runne/work/lib
          key: ${{ runner.os }}-maven-${{ hashFiles('**pom.xml') }}

      - name: build jar
        run: mvn clean package -DskipTests -Djar.finalName=helloworld-$PROJECT_VERSION

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: /home/runner/work/helloworld-java/helloworld-java/target/helloworld-1.0.0.jar

          
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'zulu'
          java-version: 17
          
      - name: "lancement des tests"
        run: mvn test
