name: workflow Version Project

on: 
  push:
    branches:
      - main

env:
  PROJECT_VERSION: 1.0.0

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: version project
        run: echo PROJECT_VERSION 

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: zulu
          java-version: 17

      - name: build jar
        run: mvn clean package -DskipTests -Djar.finalName=hello-wolrd-$PROJECT_VERSION
